services:
  postgres:
    image: postgres:18.1-alpine3.23
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: gin_user_management_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg-local-data:/var/lib/postgresql/data

volumes:
  pg-local-data:
